"""Doctor probe: graphite-managed files generated but never committed.

The failure this exists to catch (aramid interop round 24, 2026-07-31): a
generated file left uncommitted is worse than a stale one, because the
staleness is invisible from the machine that generated it. `git status` looks
clean-ish to its author while every clone and every CI checkout gets the old
version. Measured live -- six graphite-managed files sat uncommitted in
aramid's repo for a day.

Severity rule, inherited from `check_hooks`: a repo with no `GRAPHITE.md` is
deliberately not onboarded and is NOT a finding.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from graphite.doctor import check_managed_docs
from graphite.init import PLATFORMS, managed_doc_paths


# S603/S607 justification for this module's three `git` invocations: every
# argv below is a fixed literal plus a pytest `tmp_path`, so there is no
# untrusted input, and resolving git by absolute path would make the fixture
# non-portable across the CI runner and this machine. Suppressed inline rather
# than via `tests/** = [...]` in pyproject: that per-file-ignores entry is
# scoped to S101 on purpose, and its comment says the other flake8-bandit rules
# stay live because they "can still catch genuine problems in test helpers".
# Widening it to keep this file quiet would trade a real check for convenience.


def _repo(tmp_path: Path, *, onboarded: bool = True) -> Path:
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)  # noqa: S603, S607
    if onboarded:
        (tmp_path / "GRAPHITE.md").write_text("x", encoding="utf-8")
    return tmp_path


def _commit_all(root: Path) -> None:
    subprocess.run(["git", "-C", str(root), "add", "-A"], check=True)  # noqa: S603, S607
    subprocess.run(  # noqa: S603
        ["git", "-C", str(root), "-c", "user.email=t@t", "-c", "user.name=t",  # noqa: S607
         "commit", "-qm", "x"],
        check=True,
    )


def test_reports_a_managed_file_generated_but_never_committed(tmp_path: Path) -> None:
    """The round-24 case: written to the tree, never landed in git."""
    root = _repo(tmp_path)

    check = check_managed_docs(root)

    assert check.status == "degraded"
    assert "GRAPHITE.md" in check.details["uncommitted"]
    assert check.remediation


def test_reports_a_managed_file_modified_since_it_was_committed(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    _commit_all(root)
    (root / "GRAPHITE.md").write_text("regenerated by a later init", encoding="utf-8")

    check = check_managed_docs(root)

    # A tuple, not a list: DoctorCheck freezes details recursively.
    assert check.status == "degraded"
    assert check.details["uncommitted"] == ("GRAPHITE.md",)


def test_ready_when_every_managed_file_is_committed(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / "CLAUDE.md").write_text("pointer", encoding="utf-8")
    _commit_all(root)

    check = check_managed_docs(root)

    assert check.status == "ready"
    assert check.details["uncommitted"] == ()


def test_unmanaged_dirty_files_are_not_reported(tmp_path: Path) -> None:
    """Only graphite's own generated files. Ordinary work in progress is not
    doctor's business and reporting it would make the check noise."""
    root = _repo(tmp_path)
    _commit_all(root)
    (root / "src.py").write_text("print(1)", encoding="utf-8")

    check = check_managed_docs(root)

    assert check.status == "ready"


def test_optional_when_the_repository_is_not_onboarded(tmp_path: Path) -> None:
    root = _repo(tmp_path, onboarded=False)

    check = check_managed_docs(root)

    assert check.status == "optional"
    assert check.details["onboarded"] is False


def test_optional_when_git_is_unavailable(tmp_path: Path) -> None:
    """Not a git repo at all: nothing to compare against, and an un-versioned
    directory is a legitimate state -- never a finding."""
    (tmp_path / "GRAPHITE.md").write_text("x", encoding="utf-8")

    check = check_managed_docs(tmp_path)

    assert check.status == "optional"


def test_managed_doc_paths_covers_every_platform(tmp_path: Path) -> None:
    """Drift guard: the probe derives its file set from PLATFORMS, so adding a
    platform to init cannot silently leave its file unwatched."""
    covered = {path.as_posix() for path in managed_doc_paths()}

    for spec in PLATFORMS.values():
        for rel in spec.files:
            assert rel in covered, f"{rel} is generated by init but not watched"
    assert "GRAPHITE.md" in covered
    assert ".claude/settings.json" in covered
