"""Doctor probe: graphite-managed files generated but never committed.

The failure this exists to catch (aramid interop round 24, 2026-07-31): a
generated file left uncommitted is worse than a stale one, because the
staleness is invisible from the machine that generated it. `git status` looks
clean-ish to its author while every clone and every CI checkout gets the old
version. Measured live -- six graphite-managed files sat uncommitted in
aramid's repo for a day.

Severity rule, inherited from `check_hooks`: a repo with no `GRAPHITE.md` is
deliberately not onboarded and is NOT a finding.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from graphite.bootstrap import ensure_gitignore
from graphite.doctor import check_managed_docs
from graphite.hookshim import CHAINED_SUFFIX, MARKER_START
from graphite.init import (
    PLATFORMS,
    ensure_gitignore_allowlist,
    gitignored_managed_paths,
    managed_doc_paths,
)


# S603/S607 justification for this module's three `git` invocations: every
# argv below is a fixed literal plus a pytest `tmp_path`, so there is no
# untrusted input, and resolving git by absolute path would make the fixture
# non-portable across the CI runner and this machine. Suppressed inline rather
# than via `tests/** = [...]` in pyproject: that per-file-ignores entry is
# scoped to S101 on purpose, and its comment says the other flake8-bandit rules
# stay live because they "can still catch genuine problems in test helpers".
# Widening it to keep this file quiet would trade a real check for convenience.


def _repo(tmp_path: Path, *, onboarded: bool = True) -> Path:
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)  # noqa: S603, S607
    if onboarded:
        (tmp_path / "GRAPHITE.md").write_text("x", encoding="utf-8")
    return tmp_path


def _commit_all(root: Path) -> None:
    subprocess.run(["git", "-C", str(root), "add", "-A"], check=True)  # noqa: S603, S607
    subprocess.run(  # noqa: S603
        ["git", "-C", str(root), "-c", "user.email=t@t", "-c", "user.name=t",  # noqa: S607
         "commit", "-qm", "x"],
        check=True,
    )


def test_reports_a_managed_file_generated_but_never_committed(tmp_path: Path) -> None:
    """The round-24 case: written to the tree, never landed in git."""
    root = _repo(tmp_path)

    check = check_managed_docs(root)

    assert check.status == "degraded"
    assert "GRAPHITE.md" in check.details["uncommitted"]
    assert check.remediation


def test_reports_a_managed_file_modified_since_it_was_committed(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    _commit_all(root)
    (root / "GRAPHITE.md").write_text("regenerated by a later init", encoding="utf-8")

    check = check_managed_docs(root)

    # A tuple, not a list: DoctorCheck freezes details recursively.
    assert check.status == "degraded"
    assert check.details["uncommitted"] == ("GRAPHITE.md",)


def test_ready_when_every_managed_file_is_committed(tmp_path: Path) -> None:
    root = _repo(tmp_path)
    (root / "CLAUDE.md").write_text("pointer", encoding="utf-8")
    _commit_all(root)

    check = check_managed_docs(root)

    assert check.status == "ready"
    assert check.details["uncommitted"] == ()


def test_unmanaged_dirty_files_are_not_reported(tmp_path: Path) -> None:
    """Only graphite's own generated files. Ordinary work in progress is not
    doctor's business and reporting it would make the check noise."""
    root = _repo(tmp_path)
    _commit_all(root)
    (root / "src.py").write_text("print(1)", encoding="utf-8")

    check = check_managed_docs(root)

    assert check.status == "ready"


def test_optional_when_the_repository_is_not_onboarded(tmp_path: Path) -> None:
    root = _repo(tmp_path, onboarded=False)

    check = check_managed_docs(root)

    assert check.status == "optional"
    assert check.details["onboarded"] is False


def test_optional_when_git_is_unavailable(tmp_path: Path) -> None:
    """Not a git repo at all: nothing to compare against, and an un-versioned
    directory is a legitimate state -- never a finding."""
    (tmp_path / "GRAPHITE.md").write_text("x", encoding="utf-8")

    check = check_managed_docs(tmp_path)

    assert check.status == "optional"


def test_reports_a_managed_file_that_gitignore_makes_unreachable(tmp_path: Path) -> None:
    """The false-clean this probe shipped with, measured live in `BytesAI
    Learning` on 2026-07-31: `.gitignore` denies `.claude/`, so `init` wrote
    `.claude/settings.json` -- the file carrying the graph-first hook -- into a
    path git will never take. `git status --porcelain` omits ignored files
    entirely, so the probe called that file fine while listing its five
    neighbours as uncommitted.

    Worse than uncommitted, and reported separately for that reason: an
    uncommitted file is one `git add` from correct, while this one silently
    re-ignores itself forever. The old remediation is actively wrong here --
    committing it produces no change at all.
    """
    root = _repo(tmp_path)
    (root / ".gitignore").write_text(".claude/\n", encoding="utf-8")
    (root / ".claude").mkdir()
    (root / ".claude" / "settings.json").write_text("{}", encoding="utf-8")
    _commit_all(root)

    check = check_managed_docs(root)

    assert check.status == "degraded"
    assert check.details["unreachable"] == (".claude/settings.json",)
    # Not double-reported: it is not "uncommitted", it is un-committable.
    assert ".claude/settings.json" not in check.details["uncommitted"]
    assert any("gitignore" in step for step in check.remediation)


def test_a_tracked_file_matching_an_ignore_rule_is_not_unreachable(tmp_path: Path) -> None:
    """`git check-ignore` answers "does a pattern match this path?", not "can a
    clone get it?" -- and those differ for an already-tracked file, where the
    ignore rule is inert. Measured live in `demo-store2`, whose `CLAUDE.md` is
    both tracked and ignore-matched. Reporting it would be a false positive in
    the opposite direction of the bug above, in the same function.
    """
    root = _repo(tmp_path)
    (root / "CLAUDE.md").write_text("pointer", encoding="utf-8")
    _commit_all(root)
    # Added after the file is tracked, exactly as demo-store2's was.
    (root / ".gitignore").write_text("CLAUDE.md\n", encoding="utf-8")
    _commit_all(root)

    check = check_managed_docs(root)

    assert check.details["unreachable"] == ()
    assert check.status == "ready"


def test_a_repo_with_nothing_ignored_still_gets_a_real_answer(tmp_path: Path) -> None:
    """`git check-ignore` exits 1 when NOTHING matches -- the healthy case.
    Reusing the `returncode != 0` guard the rest of this probe uses would drop
    every clean repo into the "could not be read from Git" branch, which is
    itself a false-clean.
    """
    root = _repo(tmp_path)
    _commit_all(root)

    check = check_managed_docs(root)

    assert check.status == "ready"
    assert check.details["unreachable"] == ()
    assert "could not be read" not in check.summary


def test_init_allowlists_a_managed_path_an_ordinary_gitignore_swallows(tmp_path: Path) -> None:
    """The cause behind the probe above, not just the symptom.

    `ensure_gitignore_allowlist` used to act only on a *default-deny* gitignore
    (a bare `/*` line). `BytesAI Learning` has an ordinary allow-by-default
    gitignore with a plain `.claude/` deny, so the repair never fired and
    `init` wrote `.claude/settings.json` into a path Git would never take --
    reporting success. Prediction (`/*`) now has a measurement alongside it.
    """
    root = _repo(tmp_path)
    (root / ".gitignore").write_text("node_modules/\n.claude/\n", encoding="utf-8")
    (root / ".claude").mkdir()
    (root / ".claude" / "settings.json").write_text("{}", encoding="utf-8")
    _commit_all(root)
    assert gitignored_managed_paths(root, [Path(".claude/settings.json")]) == (".claude/settings.json",)

    result = ensure_gitignore_allowlist(
        root / ".gitignore",
        [Path(".claude/settings.json")],
        swallowed=gitignored_managed_paths(root, [Path(".claude/settings.json")]),
    )

    assert result["changed"] is True
    assert result["reason"] == "swallowed"
    # The sandwich is preserved: settings.local.json may hold machine-local
    # secrets, so the directory is re-denied and only settings.json allowed.
    assert result["added"] == ["!/.claude/", "/.claude/*", "!/.claude/settings.json"]
    assert gitignored_managed_paths(root, [Path(".claude/settings.json")]) == ()


def test_init_leaves_an_ordinary_gitignore_alone_when_nothing_is_swallowed(tmp_path: Path) -> None:
    """Repair only what is measured. A repo whose gitignore merely looks
    unusual keeps it untouched -- rewriting someone's ignore rules on a guess
    is a worse failure than the one being fixed."""
    root = _repo(tmp_path)
    (root / ".gitignore").write_text("node_modules/\n", encoding="utf-8")
    (root / "CLAUDE.md").write_text("pointer", encoding="utf-8")
    _commit_all(root)

    before = (root / ".gitignore").read_text(encoding="utf-8")
    result = ensure_gitignore_allowlist(
        root / ".gitignore",
        [Path("CLAUDE.md")],
        swallowed=gitignored_managed_paths(root, [Path("CLAUDE.md")]),
    )

    assert result["changed"] is False
    assert result["reason"] == "not default-deny"
    assert (root / ".gitignore").read_text(encoding="utf-8") == before


def test_gitignored_managed_paths_fails_open_outside_a_repo(tmp_path: Path) -> None:
    """It gates a .gitignore rewrite, so "cannot tell" must mean "change
    nothing", never "assume swallowed"."""
    (tmp_path / "CLAUDE.md").write_text("x", encoding="utf-8")

    assert gitignored_managed_paths(tmp_path, [Path("CLAUDE.md")]) == ()


def _trampoline(path: Path) -> None:
    """A hook file shaped like one graphite wrote: carries the marker."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"#!/bin/sh\n{MARKER_START}\nexec graphite ...\n", encoding="utf-8")


def test_reports_the_vscode_task_generated_but_never_committed(tmp_path: Path) -> None:
    """`init` writes `.vscode/tasks.json` (init.py, ensure_vscode_activation_task)
    and it was NOT watched. Measured live 2026-07-31: the file sat untracked in
    aramid's repo since 07-28 while this very check ran on this machine and
    reported nothing -- which is also how I came to claim, three rounds running,
    that graphite had never written there."""
    root = _repo(tmp_path)
    _commit_all(root)
    (root / ".vscode").mkdir()
    (root / ".vscode" / "tasks.json").write_text("{}", encoding="utf-8")

    check = check_managed_docs(root)

    assert check.status == "degraded"
    assert ".vscode/tasks.json" in check.details["uncommitted"]


def test_hook_trampolines_are_never_reported_as_uncommitted(tmp_path: Path) -> None:
    """Hook trampolines are MACHINE-LOCAL, not repository content, and briefly
    on 2026-07-31 this check said otherwise.

    `render_trigger_shim` embeds an absolute interpreter path -- in graphite's
    own `.githooks/post-commit`, `INTERP="/c/Python314/python.exe"`. Reporting
    it "generated but never committed" is advice that bakes one machine's
    Python location into the repo and makes every `init` on a different box
    produce a spurious diff.

    They are distributed per machine by git template (`a16b00f`) instead, which
    is why no repo on this machine has ever tracked a file under `.githooks/`.
    `check_hooks` is what reports whether they are installed and enforced;
    this probe is about files that belong in git.
    """
    root = _repo(tmp_path)
    _commit_all(root)
    _trampoline(root / ".githooks" / "post-commit")
    (root / ".githooks" / f"post-commit{CHAINED_SUFFIX}").write_text("#!/bin/sh\nmine\n", encoding="utf-8")

    check = check_managed_docs(root)

    assert check.status == "ready"
    assert check.details["uncommitted"] == ()


def _is_ignored(root: Path, rel: str) -> bool:
    """Ask git, not the pattern list. Pattern inspection passes on a wrong
    ORDERING; git evaluating the real file does not."""
    result = subprocess.run(  # noqa: S603
        ["git", "-C", str(root), "ls-files", "--others", "--ignored",  # noqa: S607
         "--exclude-standard", "--", rel],
        capture_output=True, text=True, check=True,
    )
    return bool(result.stdout.strip())


def _repair(root: Path, paths: list[Path]) -> dict:
    return ensure_gitignore_allowlist(
        root / ".gitignore", paths, swallowed=gitignored_managed_paths(root, paths)
    )


def test_default_deny_repo_gets_the_vscode_task_allowlisted(tmp_path: Path) -> None:
    """demo-store2's shape: `/*` denies everything and graphite's allowlist
    covered only the six instruction files, so `.vscode/tasks.json` -- which
    `init` also writes, and which IS portable (`python -m graphite activate .`,
    no absolute paths) -- was unreachable."""
    root = _repo(tmp_path)
    (root / ".gitignore").write_text("/*\n!/.gitignore\n!/GRAPHITE.md\n", encoding="utf-8")
    (root / ".vscode").mkdir()
    (root / ".vscode" / "tasks.json").write_text("{}", encoding="utf-8")
    _commit_all(root)
    assert _is_ignored(root, ".vscode/tasks.json")

    _repair(root, [Path(".vscode/tasks.json")])

    assert not _is_ignored(root, ".vscode/tasks.json")


def test_the_hooks_directory_is_never_allowlisted(tmp_path: Path) -> None:
    """The counterpart to the probe change: `init` must not un-ignore
    `.githooks/` out of a default-deny gitignore. Doing so invites committing a
    trampoline carrying this machine's interpreter path, and would also expose
    `post-commit.local` -- the private hook graphite chained to but never
    wrote."""
    root = _repo(tmp_path)
    (root / ".gitignore").write_text("/*\n!/.gitignore\n!/GRAPHITE.md\n", encoding="utf-8")
    _trampoline(root / ".githooks" / "post-commit")
    (root / ".githooks" / f"post-commit{CHAINED_SUFFIX}").write_text("#!/bin/sh\nsecret\n", encoding="utf-8")
    _commit_all(root)

    _repair(root, [Path(".vscode/tasks.json"), Path(".githooks/post-commit")])

    assert _is_ignored(root, ".githooks/post-commit"), "trampolines stay machine-local"
    assert _is_ignored(root, f".githooks/post-commit{CHAINED_SUFFIX}")


def test_the_ignore_block_states_that_hooks_are_machine_local(tmp_path: Path) -> None:
    """Ignored rather than merely untracked, so the intent is written down. No
    repo on this machine has ever tracked a file under `.githooks/`; that was
    an unstated convention until it briefly got contradicted."""
    path = tmp_path / ".gitignore"
    path.write_text("node_modules/\n", encoding="utf-8")

    ensure_gitignore(path)

    assert ".githooks/" in path.read_text(encoding="utf-8").splitlines()


def test_a_partial_pre_existing_sandwich_is_repaired_not_half_repaired(tmp_path: Path) -> None:
    """A sandwich is emitted whole or not at all, never deduped pattern-by-
    pattern against what is already in the file.

    The demonstrable failure -- verified by mutation, not assumed: with
    `!/.githooks/post-commit` already present and the two directory patterns
    missing, a per-pattern dedup skips the file negation and appends only
    `!/.githooks/` and `/.githooks/*`. gitignore is last-match-wins, so the
    freshly-appended `/.githooks/*` now beats the older negation and the file
    the repair exists to rescue stays ignored. The repair silently fails.

    (The *opposite* hazard -- a half-sandwich exposing `.local` -- turns out
    not to be constructible: a trailing-slash pattern matches directories only,
    so an appended `!/.githooks/` never out-matches an earlier `/.githooks/*`
    for a file inside. Tested below in its own right anyway.)
    """
    root = _repo(tmp_path)
    (root / ".gitignore").write_text(
        "/*\n!/.gitignore\n!/GRAPHITE.md\n!/.vscode/tasks.json\n", encoding="utf-8"
    )
    _commit_all(root)
    (root / ".vscode").mkdir()
    (root / ".vscode" / "tasks.json").write_text("{}", encoding="utf-8")
    (root / ".vscode" / "settings.local.json").write_text("{}", encoding="utf-8")

    _repair(root, [Path(".vscode/tasks.json")])

    assert not _is_ignored(root, ".vscode/tasks.json"), "the repair must actually reach the file"
    assert _is_ignored(root, ".vscode/settings.local.json"), "and must not expose its neighbours"


def test_the_repair_is_idempotent(tmp_path: Path) -> None:
    """Driven by measurement, so a second run has nothing swallowed to fix and
    must not churn the file."""
    root = _repo(tmp_path)
    (root / ".gitignore").write_text("/*\n!/.gitignore\n!/GRAPHITE.md\n", encoding="utf-8")
    (root / ".vscode").mkdir()
    (root / ".vscode" / "tasks.json").write_text("{}", encoding="utf-8")
    _commit_all(root)
    _repair(root, [Path(".vscode/tasks.json")])
    after_first = (root / ".gitignore").read_text(encoding="utf-8")

    second = _repair(root, [Path(".vscode/tasks.json")])

    assert second["changed"] is False
    assert (root / ".gitignore").read_text(encoding="utf-8") == after_first


def test_managed_doc_paths_covers_every_platform(tmp_path: Path) -> None:
    """Drift guard: the probe derives its file set from PLATFORMS, so adding a
    platform to init cannot silently leave its file unwatched."""
    covered = {path.as_posix() for path in managed_doc_paths()}

    for spec in PLATFORMS.values():
        for rel in spec.files:
            assert rel in covered, f"{rel} is generated by init but not watched"
    assert "GRAPHITE.md" in covered
    assert ".claude/settings.json" in covered
