"""Generate docs/reference/cli.md from graphite's argparse tree.

    python scripts/gen_cli_reference.py          # rewrite the document
    python scripts/gen_cli_reference.py --check  # exit 1 if it is stale

`tests/test_cli_reference.py` runs the check, so a subcommand or option that
changes without regenerating this page fails the suite.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from graphite.cli import build_parser  # noqa: E402

OUT = ROOT / "docs" / "reference" / "cli.md"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _default(action: argparse.Action) -> str:
    if action.default in (None, argparse.SUPPRESS, False) or isinstance(action, argparse._StoreTrueAction):
        return ""
    return f" (default: `{action.default}`)"


def _option_rows(parser: argparse.ArgumentParser) -> list[str]:
    rows: list[str] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction) or action.help == argparse.SUPPRESS:
            continue
        flags = ", ".join(f"`{opt}`" for opt in action.option_strings) or f"`{action.dest}`"
        rows.append(f"| {flags} | {_cell(action.help or '')}{_default(action)} |")
    return rows


def _subcommand_help(sub: argparse._SubParsersAction, name: str) -> str:
    for choice in sub._choices_actions:
        if choice.dest == name:
            return choice.help or ""
    return ""


def render_reference() -> str:
    parser = build_parser()
    sub = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    lines = [
        "# CLI reference",
        "",
        "Generated by `python scripts/gen_cli_reference.py` from the argparse tree;",
        "`tests/test_cli_reference.py` fails when this page is stale. Global options",
        "go BEFORE the subcommand: `graphite --output-dir out build .`. Exit codes",
        "are in `docs/reference/exit-codes.md`; configuration in",
        "`docs/reference/configuration.md`.",
        "",
        "## Global options",
        "",
        "| Option | Meaning |",
        "|---|---|",
        *_option_rows(parser),
        "",
        "## Subcommands",
        "",
    ]
    seen: dict[int, str] = {}
    for name, child in sub.choices.items():
        if id(child) in seen:
            continue  # an alias shares the parser object; listed under its first name
        seen[id(child)] = name
        aliases = [alias for alias, other in sub.choices.items() if other is child and alias != name]
        lines += [f"### `graphite {name}`", ""]
        if aliases:
            lines += ["Aliases: " + ", ".join(f"`{alias}`" for alias in aliases), ""]
        description = _subcommand_help(sub, name) or (child.description or "")
        if description:
            lines += [_cell(description), ""]
        rows = _option_rows(child)
        if rows:
            lines += ["| Option | Meaning |", "|---|---|", *rows, ""]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 when docs/reference/cli.md is stale instead of rewriting it")
    arguments = parser.parse_args(argv)
    rendered = render_reference()
    if arguments.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(f"stale: {OUT} -- run python scripts/gen_cli_reference.py", file=sys.stderr)
            return 1
        print("cli reference is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
