"""Generate docs/reference/cli.md from graphite's argparse tree.

    python scripts/gen_cli_reference.py          # rewrite the document
    python scripts/gen_cli_reference.py --check  # exit 1 if it is stale

`tests/test_cli_reference.py` runs the check, so a subcommand or option that
changes without regenerating this page fails the suite.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from graphite.cli import build_parser  # noqa: E402

OUT = ROOT / "docs" / "reference" / "cli.md"

#: Argument destinations whose default is `str(default_projects_root())` in
#: cli.py -- the only defaults that come from the environment.
_ENVIRONMENT_DERIVED_DESTS = frozenset({"base_path"})


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _default(action: argparse.Action) -> str:
    if action.default in (None, argparse.SUPPRESS, False) or isinstance(action, argparse._StoreTrueAction):
        return ""
    rendered = str(action.default)
    # Defaults derived from the environment are the machine's, not the
    # tool's. The first cut of this page rendered `F:\Projects` -- the value
    # of GRAPHITE_PROJECTS_ROOT on the maintainer's box -- and the lockstep
    # test then failed on every CI leg, where the same default is `.`. Name
    # the rule, never the value. Keyed on the DESTINATION, not the value: with
    # the variable unset the value is `.`, which is also the honest default
    # of every plain `path` argument and must keep rendering as `.`.
    if action.dest in _ENVIRONMENT_DERIVED_DESTS or Path(rendered).is_absolute():
        return " (default: the projects root -- `GRAPHITE_PROJECTS_ROOT`, else the current directory)"
    return f" (default: `{rendered}`)"


def _option_rows(parser: argparse.ArgumentParser) -> list[str]:
    rows: list[str] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction) or action.help == argparse.SUPPRESS:
            continue
        flags = ", ".join(f"`{opt}`" for opt in action.option_strings) or f"`{action.dest}`"
        rows.append(f"| {flags} | {_cell(action.help or '')}{_choices(action)}{_default(action)} |")
    return rows


def _choices(action: argparse.Action) -> str:
    """An argument that restricts its values names them. `graphite channel`
    dispatches on a positional with `choices` rather than a subparser, so
    without this the page could not say that `report`, `list`, `show` and
    `register` exist."""
    if not action.choices:
        return ""
    return " (one of: " + ", ".join(f"`{choice}`" for choice in action.choices) + ")"


def _subcommand_help(sub: argparse._SubParsersAction, name: str) -> str:
    for choice in sub._choices_actions:
        if choice.dest == name:
            return choice.help or ""
    return ""


def _nested_subparsers(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    return next((a for a in parser._actions if isinstance(a, argparse._SubParsersAction)), None)


def _render_commands(lines: list[str], sub: argparse._SubParsersAction, *, prefix: str, level: int) -> None:
    """Render every command under `sub`, then recurse into each command that
    is itself a group. The first cut walked only the top level, so the
    twenty-four commands one level down -- `route reconcile`, `incidents ack`
    -- and every option they own were absent from the page, and the lockstep
    test could not see them drift. Aliases share a parser object and are
    listed under their first name."""
    seen: dict[int, str] = {}
    for name, child in sub.choices.items():
        if id(child) in seen:
            continue
        seen[id(child)] = name
        aliases = [alias for alias, other in sub.choices.items() if other is child and alias != name]
        lines += [f"{'#' * level} `graphite {prefix}{name}`", ""]
        if aliases:
            lines += ["Aliases: " + ", ".join(f"`{alias}`" for alias in aliases), ""]
        description = _subcommand_help(sub, name) or (child.description or "")
        if description:
            lines += [_cell(description), ""]
        rows = _option_rows(child)
        if rows:
            lines += ["| Option | Meaning |", "|---|---|", *rows, ""]
        nested = _nested_subparsers(child)
        if nested is not None:
            names = sorted({nested_name for nested_name in nested.choices})
            lines += [
                "Subcommands: " + ", ".join(f"`{prefix}{name} {nested_name}`" for nested_name in names),
                "",
            ]
            _render_commands(lines, nested, prefix=f"{prefix}{name} ", level=level + 1)


def render_reference() -> str:
    parser = build_parser()
    sub = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    lines = [
        "# CLI reference",
        "",
        "Generated by `python scripts/gen_cli_reference.py` from the argparse tree;",
        "`tests/test_cli_reference.py` fails when this page is stale. Global options",
        "go BEFORE the subcommand: `graphite --output-dir out build .`. A group's",
        "commands (`graphite route reconcile`) are rendered under the group. Exit",
        "codes are in `docs/reference/exit-codes.md`; configuration in",
        "`docs/reference/configuration.md`.",
        "",
        "## Global options",
        "",
        "| Option | Meaning |",
        "|---|---|",
        *_option_rows(parser),
        "",
        "## Subcommands",
        "",
    ]
    _render_commands(lines, sub, prefix="", level=3)
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 when docs/reference/cli.md is stale instead of rewriting it")
    arguments = parser.parse_args(argv)
    rendered = render_reference()
    if arguments.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(f"stale: {OUT} -- run python scripts/gen_cli_reference.py", file=sys.stderr)
            return 1
        print("cli reference is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
